server:
  port: 9195
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profileDB?createDatabaseIfNotExist=true
    username: vivek
    password: vivek
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: profile
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
